version: '3'

services:
  webscrapping:
    build:
      context: Python/webscrapping
      dockerfile: Dockerfile
    ports:
      - "5003:5001"
    depends_on:
      - mongo

  registro:
    build:
      context: Python/registro
      dockerfile: Dockerfile
    ports:
      - "5004:5002"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
